/**
 * 默认配置与旧选项名兼容映射
 */

export const DEFAULT_OPTIONS = {
  images: [],
  props: { url: 'url', title: 'title', thumbnail: 'thumbnail' },
  backdrop: false,
  minZoomRatio: 0.1,
  maxZoomRatio: 5,
  loop: true,
  retryOnError: false,
  /** 未显式提供 orientation 时，自动解析 JPEG EXIF 方向（额外请求图片字节流，默认关闭） */
  autoOrientation: false,
  defaultFallbackImage: '',
  zIndex: 5000,
  className: 'images-viewer',
  showThumbBar: true,
  showTitle: true,
  showCounter: true,
  showNavButtons: true,
  itemClass: '',
  activeItemClass: '',
  errorClass: '',
  buttons: {
    zoomIn: true,
    zoomOut: true,
    rotateLeft: true,
    rotateRight: true,
    reset: true,
    download: true,
    copy: false,
    fullscreen: true,
    prev: true,
    next: true,
    close: true,
    topClose: true,
    thumbnails: true,
    info: true,
  },
  customButtons: [],
  initialViewIndex: 0,
  imageInfo: { visible: false, showName: true, showDimensions: true },
  i18n: {
    buttons: { prev: '上一张', next: '下一张', close: '关闭', loading: '加载中...' },
    info: { name: '名称:', dimensions: '尺寸:' },
    helpTitle: '操作指引',
    helpKeys: '快捷键',
    helpGestures: '手势',
    helpButtons: '按钮',
  },
  theme: {
    viewerBgColor: 'rgba(0,0,0,0.85)',
    toolbarBgColor: 'rgba(40,40,40,0.8)',
    toolbarBorderRadius: '30px',
    toolbarPadding: '8px 16px',
    toolbarBottom: '24px',
    buttonBgColor: 'rgba(255,255,255,0.1)',
    buttonHoverBg: 'rgba(255,255,255,0.25)',
    buttonSize: '40px',
    buttonFontSize: '18px',
    buttonBorderRadius: '50%',
    navButtonBgColor: 'rgba(255,255,255,0.1)',
    navButtonHoverBg: 'rgba(255,255,255,0.25)',
    navButtonSize: '48px',
    navButtonFontSize: '20px',
    navButtonBorderRadius: '50%',
    topCloseBtnSize: '44px',
    topCloseBtnTop: '16px',
    topCloseBtnRight: '16px',
    topCloseBtnFontSize: '22px',
    topCloseBtnBgColor: 'rgba(255,255,255,0.1)',
    topCloseBtnHoverBg: 'rgba(255,255,255,0.25)',
    infoBgColor: 'rgba(40,40,40,0.8)',
    infoBorderRadius: '8px',
    infoPadding: '10px 14px',
    infoFontSize: '13px',
    infoTop: '60px',
    infoLeft: '16px',
    zoomIndicatorBg: 'rgba(40,40,40,0.8)',
    zoomIndicatorBorderRadius: '16px',
    zoomIndicatorPadding: '6px 12px',
    zoomIndicatorFontSize: '13px',
    zoomIndicatorTop: '16px',
    zoomIndicatorLeft: '16px',
    activeColor: '#4a9eff',
    textColor: '#fff',
    transitionSpeed: '0.3s',
    thumbItemWidth: 80,
    thumbItemHeight: 56,
    thumbGap: 10,
    thumbBarHeight: 90,
  },
  onShow: null,
  onClose: null,
  onChange: null,
  onRotate: null,
  onDrag: null,
  onZoom: null,
  onImageError: null,
  onInfo: null,
  onCounter: null,
}

// 旧选项名 → 新选项名 兼容映射
export const OPTION_ALIASES = {
  minScale: 'minZoomRatio',
  maxScale: 'maxZoomRatio',
  namespace: 'className',
  closeOnMaskClick: 'backdrop',
  initialIndex: 'initialViewIndex',
}
